name: tests

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3

  test:
    needs: lint
    strategy:
      matrix:
        go: [1.18.x, 1.19.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go test -race -covermode atomic -coverprofile=covprofile ./...
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ github.token }}
          GIT_BRANCH: ${{ github.head_ref }}
        run: goveralls -parallel -coverprofile=covprofile -service=github -flagname="${{ runner.os }}-Go-${{ matrix.go }}"

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ github.token }}
          GIT_BRANCH: ${{ github.head_ref }}
        run: goveralls -parallel-finish -service=github
